spring:
  datasource:
    url: jdbc:h2:mem:app_db;DB_CLOSE_DELAY=-1   
    username: sa
    password: 
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      
      show-sql: true
      
    